### ISSUE TITLE
Incorporate Catalyst

### ISSUE THREAD

**Issue by RobQuistNL** [Kezarus-tech/Monastery-Framework_GM2#1]
A shameless plug + request to combine efforts :)

I've been working on Catalyst for a while; https://github.com/GameMakerHub/Catalyst (https://www.gamemakerhub.net/ ) which is a package / dependency manager for GM.

A few possibilities I see here;

1) splitting up this project into smaller (reusable) components - easy updating and smaller code footprints
2) An idea I have for catalyst is to support templates, where you can call a simple CLI command to generate a template game project with features you'd like (much like the example games in GM).

Maybe there's some nice collaboration options for us here? :)

**Comment by Kezarus-tech** [comment]
Hi mate! Thanks for your comments on my project. =]

1. About splitting the Framework, well, I thought about that at the start, but the real focus here is making a plataform for games and be a burdenless experience. So your button is drawn by a 9-slices, and have sound and language support. If I separate those features from one another the developer would have to waste their time doing that. And it's easier to remove the features than to put them back on. So... ¯\_(ツ)_/¯

2. This idea is fantastic! Tell me more about it! But I have no idea on how could I help on that.

I see that we can collaborate. Let's talk more about this. =]

**Comment by RobQuistNL** [comment]
Cool! I see what you mean, but catalyst actually solves this problem exactly - if you'd split up your project into multiple smaller ones, you could make this project depend on all those smaller projects. Using catalyst it'd be a breeze;

```json
{
    "name": "Kezarus-tech/Monastery-template",
    "description": "Open source game template",
    "license": "MIT",
    "homepage": "https://github.com/Kezarus-tech/Monastery-template",
    "yyp": "monastery-template.yyp",
    "require": {
        "Kezarus-tech/monastery-audio-engine": ">=1.0",
        "Kezarus-tech/monastery-ui": ">=1.2",
        "Kezarus-tech/monastery-intl": ">=2.1",
    }
}
```
The monastery-ui would for example look like;

```json
{
    "name": "Kezarus-tech/Monastery-ui",
    "description": "Open source game UI framework",
    "license": "MIT",
    "homepage": "https://github.com/Kezarus-tech/Monastery-ui",
    "yyp": "monastery-ui.yyp",
    "require": {
        "Kezarus-tech/monastery-audio-engine": ">=1.0",
        "Kezarus-tech/monastery-9slice": "*",
        "Kezarus-tech/monastery-input-devices": "1.4.2",
    }
}
```

If you'd run `catalyst install` in your main project, it would then solve all the dependencies recursively and install those into your project. Updating subprojects would be very easy this way, too.

So this would be best of both worlds:
1) People that only need your audio engine, only have to include `Kezarus-tech/monastery-audio-engine`
2) People that want the entire template, only have to include that one (it includes the rest)
3) Every small part of the framework can be independently developed and tested (without cluttering the other frameworks)

Catalyst unfortunately doesn't have support for "templates" yet, but this would be a very nice playground to get that to work. We could try pulling this framework apart into smaller sets like written out above? I haven't looked into this project entirely just yet, but i'd be happy to help out!

**Comment by Kezarus-tech** [comment]
Hi mate! Sorry for the late response. As much as I found this proposal interesting, as more people could be aided by these tools, this will add some complexity to the user (a thing that I want to avoid).

As much as I love Game Maker, it doesn't have the basic features for us to separate the framework and stitch the parts back together seemingly (like dependency injection and interfaces). I don't have a clue where to start on that. o.O

On top of that, to separate things is something that I want to avoid. As there are plenty of the features that I offer on the Framework scattered at Yoyo Marketplace. The problem that I find is to sew them together to work as one thing.

Catalyst is a very interesting tool that Game Maker is in dire need of. We need something akin to a Maven-like structure to manage dependencies. I hope you can achieve what you are looking for with it. =]

**Comment by RobQuistNL** [comment]
Hey @Kezarus-tech! No problem, I understand your concerns :) 

I'm secretly hoping 2.3 will provide some updates that will make it much easier to split up projects and allow for reusability.

Thanks for considering! Good luck with the project.

Cheers
